config/routes.rb
 Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'streams' => 'streams#index'

  get 'posts/new'

  get 'relationships/new'

  
  
  resources :users do
      member do
          get :following
      end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

end

app/models/stream.rb
class Stream < ActiveRecord::Base
	has_many :relationships, dependent: :destroy

	def followers
		follower_ids = "SELECT follower_id FROM relationships WHERE followed_id = :stream_id"
	end

end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  def new
  end

   def send_all
     stream = Stream.find(params[:id])
     followers = stream.followers
     body = get_tweet(stream)
     send_message(followers, body)
   end
end



streams = {
	"Tech" => ["TheHackerNews", "TechCrunch", "newsycombinator"],
	"Politics" => ["politicalwire", "BBC", "NPR", "nytimes"],
	"Sports" => ["espn"],
	"Finance" => ["EconBizFin", "financialtimes"]
}

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/streams/_card.html.erb
<div class="card" id-"card-<%= stream.name %>">
	<img class="card-img-top" data-src="../../images/<%= stream.name %>" alt="Card image">
	<div claass="card-block">
		<h4 class="card-title"><%= stream.name %></h4>
		<p class="card-text"><%= stream.description %></p>
		<%= link_to "Follow", relationship_path, method: :post %>
	</div>
</div>

app/views/streams/index.html.erb
<% provide(:title, 'Streams') %>
<h1>Streams</h1>

app/views/streams/new.html.erb
<h1>Streams#new</h1>
<p>Find me in app/views/streams/new.html.erb</p>