config/routes.rb
 Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'streams' => 'streams#index'

  get 'posts/new'

  get 'relationships/new'

  
  
  resources :users do
      member do
          get :following
      end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Soapbox by Andrew Chen</small>
  
    <ul class="nav nav-inline">
      <li class="nav-item"><%= link_to "About", '#' %></li>
      <li class="nav-item"><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "soapbox", root_path, id: "logo" %>
    <nav class="navbar navbar-light bg-faded">
      <ul class="nav navbar-nav pull-xs-right">
        <li class="nav-item"><%= link_to "Home", root_path %></li>
        <li class="nav-item"><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "Users", users_path %></li>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="dropdown-item"><%= link_to "Profile", current_user %></li>
              <li class="dropdown-item"><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item">
                <%= link_to  "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Soapbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>